"""Persistent knowledge graph views built from immutable repositories."""

from .acquisition import (
    AcquisitionError,
    ArticleURLResolver,
    DOIResolver,
    HTMLLiteratureTextExtractor,
    HTMLTextExtraction,
    HTTPResponse,
    LiteratureAcquisitionService,
    LocalPDFResolver,
    PinnedHTTPTransport,
    ResourceResolver,
    SafeHTTPError,
    SafeHTTPFetcher,
    detect_acquisition_input,
    normalize_doi,
    validate_literature_representation,
)
from .graph import KnowledgeGraphBuilder, KnowledgeGraphError
from .collection import (
    CollectionConnector,
    CollectionError,
    CollectionImportService,
    GenericHTMLCollectionConnector,
    canonicalize_url,
    diff_collection_snapshots,
    make_collection_definition,
    make_collection_scope_policy,
    path_matches_prefix,
)
from .ingestion import (
    LiteratureIngestionService,
    LiteratureExtractionError,
    LiteratureMetadata,
    LiteratureTextExtractor,
    PypdfLiteratureTextExtractor,
    LiteratureRepresentationSelector,
    create_evidence_span_from_canonical_text,
    validate_literature_ingestion_chain,
)
from .mermaid import knowledge_graph_to_mermaid
from .evidence_migration import (
    KnowledgeEvidenceMigrationResult,
    migrate_knowledge_evidence,
)
from .trust import TrustedKnowledgeError, TrustedKnowledgeValidator
from .structure import (
    DocumentStructureExtractionResult,
    DocumentStructureExtractor,
    DocumentStructureInput,
    DocumentStructureService,
    HTMLDocumentStructureExtractor,
    PDFDocumentStructureExtractor,
    create_evidence_from_block,
    create_evidence_from_figure_caption,
    create_evidence_from_table_cell,
    format_structured_evidence_locator,
    inspect_document_structure,
    validate_document_structure,
    verify_structured_evidence_locator,
)

__all__ = [
    "AcquisitionError",
    "ArticleURLResolver",
    "DOIResolver",
    "HTMLLiteratureTextExtractor",
    "HTMLTextExtraction",
    "HTTPResponse",
    "CollectionConnector",
    "CollectionError",
    "CollectionImportService",
    "GenericHTMLCollectionConnector",
    "KnowledgeGraphBuilder",
    "KnowledgeGraphError",
    "KnowledgeEvidenceMigrationResult",
    "TrustedKnowledgeError",
    "TrustedKnowledgeValidator",
    "DocumentStructureExtractionResult",
    "DocumentStructureExtractor",
    "DocumentStructureInput",
    "DocumentStructureService",
    "HTMLDocumentStructureExtractor",
    "PDFDocumentStructureExtractor",
    "LiteratureIngestionService",
    "LiteratureAcquisitionService",
    "LiteratureExtractionError",
    "LiteratureMetadata",
    "LiteratureTextExtractor",
    "PypdfLiteratureTextExtractor",
    "LiteratureRepresentationSelector",
    "LocalPDFResolver",
    "PinnedHTTPTransport",
    "ResourceResolver",
    "SafeHTTPError",
    "SafeHTTPFetcher",
    "create_evidence_span_from_canonical_text",
    "create_evidence_from_block",
    "create_evidence_from_figure_caption",
    "create_evidence_from_table_cell",
    "validate_literature_ingestion_chain",
    "detect_acquisition_input",
    "knowledge_graph_to_mermaid",
    "migrate_knowledge_evidence",
    "normalize_doi",
    "validate_literature_representation",
    "canonicalize_url",
    "diff_collection_snapshots",
    "make_collection_definition",
    "make_collection_scope_policy",
    "path_matches_prefix",
    "format_structured_evidence_locator",
    "inspect_document_structure",
    "validate_document_structure",
    "verify_structured_evidence_locator",
]
